#!/bin/bash

info () { echo "[$(date +"%Y-%m-%dT%H:%M:%S%z")] [INFO    ] (${FUNCNAME[1]}) $@" | tr '\n' ' '; echo ""; }
warn () { echo "[$(date +"%Y-%m-%dT%H:%M:%S%z")] [WARNING ] (${FUNCNAME[1]}) $@" | tr '\n' ' '; echo ""; }
crit () { echo "[$(date +"%Y-%m-%dT%H:%M:%S%z")] [CRITICAL] (${FUNCNAME[1]}) $@" | tr '\n' ' '; echo ""; exit 1; }

run_cmd () {
    local CMD="$*"
    info "Running: ${CMD}"
    set -o pipefail
    (eval "$CMD" 2>&1) | while IFS= read -r LINE; do
        info "$LINE"
    done
    EXIT_CODE=${PIPESTATUS[0]}
    set +o pipefail
    info "Command completed with exit code: ${EXIT_CODE}"
    [ ${EXIT_CODE} -ne 0 ] && crit "Failed to run, see above for details"
}

check_debug () {
    [ "${FP_DEBUG}" = "true" ] && set -x
}

check_dependencies () {
    [ "$EUID" != "0" ] && crit "Re-run as root or with sudo"
    command -v curl &> /dev/null || crit "Requirement 'curl' is not installed on this machine, please install and re-run."
}

check_variables () {
    if ! [ "$FP_CLUSTER_TOKEN" ]; then
        warn "Environment variable 'FP_CLUSTER_TOKEN' is not set."
        warn "Setup will use 'unmanaged' mode"
        warn "You can obtain a token from https://fairport.io"
        warn "If you have a token you can set it with 'export FP_CLUSTER_TOKEN=<YOUR_TOKEN>'"
    else
        info "Setup will use 'managed' mode"
    fi
    MODE="$FP_MODE"
    OS="$(uname | tr '[:upper:]' '[:lower:]')"
    ARCH="$(uname -m | tr '[:upper:]' '[:lower:]')"
    echo "$ARCH" | egrep -q "amd64|x86_64" && ARCH="amd64"
    echo "$ARCH" | egrep -q "arm64|aarch64" && ARCH="arm64"
    RKE2_VERSION="v1.33.3+rke2r1"
    RKE2_VERSION_URLSAFE=$(echo "$RKE2_VERSION" | sed 's/+/%2B/g')
    RKE2_IMAGE_URL="https://github.com/rancher/rke2/releases/download/${RKE2_VERSION_URLSAFE}/rke2-images.${OS}-${ARCH}.tar.zst"
    RKE2_IMAGE_DIR="/var/lib/rancher/rke2/agent/images"
    RKE2_IMAGE_FILE="${RKE2_IMAGE_DIR}/rke2-images.${OS}-${ARCH}.tar.zst"
    RKE2_BINARY_URL="https://github.com/rancher/rke2/releases/download/${RKE2_VERSION_URLSAFE}/rke2.${OS}-${ARCH}.tar.gz"
    RKE2_BINARIES_DIR="/var/lib/rancher/rke2/bin"
    RKE2_BINARIES_BUNDLE_FILE="${RKE2_BINARIES_DIR}/rke2.${OS}-${ARCH}-${RKE2_VERSION}.tar.gz"
    RKE2_BINARY_FILE="/usr/local/bin/rke2"
}

k8s_same_version () {
    local EXISTING_RKE2_VERSION
    EXISTING_RKE2_VERSION=$(rke2 --version 2>&1 | grep -o "v[0-9]\S*")
    [ "$EXISTING_RKE2_VERSION" = "$RKE2_VERSION" ]
}

k8s_is_healthy () {
    local CMD='fpk -n kube-system get pods 2>&1 | egrep -v "NAME|Running|Completed" | wc -l'
    local STATUS
    STATUS=$(timeout 10 bash -c "$CMD" 2>&1)
    if [ "$STATUS" -eq 0 ]; then
        info "Cluster health: OK"
        return 0
    else
        info "Cluster health: NOT OK"
        return 1
    fi
}

wait_for_k8s_ready () {
    local MAX_RETRIES=$1
    while ! k8s_is_healthy; do
        [ $MAX_RETRIES -le 0 ] && crit "Containers in kube-system didn't start, refer to documentation: TODO"
        info "Waiting for all containers in kube-system to start ($MAX_RETRIES retries left)"
        MAX_RETRIES=$(($MAX_RETRIES - 1))
        sleep 1
    done
}

generate_rke2_config () {
    info "Generating rke2 config file"
    local NODE_NAME=$(cat /etc/machine-id 2>/dev/null) || NODE_NAME=$(date | md5sum | cut -d ' ' -f1)
    mkdir -p /etc/rancher/rke2
    cat << EOF > /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0600"
node-name: "$NODE_NAME"
cluster-cidr: "100.64.0.0/12"
service-cidr: "100.80.0.0/12"
etcd-expose-metrics: true
etcd-arg: "quota-backend-bytes=8589934592"
EOF
}

install_kubernetes () {
    EXISTING_RKE2_VERSION=$(rke2 --version 2>&1 | grep -o "v[0-9]\S*")
    if [ "$EXISTING_RKE2_VERSION" != "$RKE2_VERSION" ]; then
        [ ! -f "$RKE2_BINARY_FILE" ] && info "Installing rke2 ($RKE2_VERSION) from $RKE2_BINARY_URL"
        [ -f "$RKE2_BINARY_FILE" ] && info "Upgrading rke2 ($RKE2_VERSION) from $RKE2_BINARY_URL"
        run_cmd mkdir -p $RKE2_BINARIES_DIR/$RKE2_VERSION
        [ ! -f "$RKE2_BINARIES_BUNDLE_FILE" ] && run_cmd curl -sL $RKE2_BINARY_URL -o $RKE2_BINARIES_BUNDLE_FILE
        run_cmd tar -xf $RKE2_BINARIES_BUNDLE_FILE -C $RKE2_BINARIES_DIR/$RKE2_VERSION
        run_cmd cp $RKE2_BINARIES_DIR/$RKE2_VERSION/bin/* /usr/local/bin/
        run_cmd cp $RKE2_BINARIES_DIR/$RKE2_VERSION/lib/systemd/system/rke2* /etc/systemd/system/
        generate_rke2_config
    fi

    run_cmd systemctl daemon-reload
    run_cmd systemctl enable rke2-server.service
    run_cmd systemctl start rke2-server.service

    info "Install fpk"
    run_cmd mkdir -p /usr/local/bin
    echo -e '#!/bin/bash\n\n/var/lib/rancher/rke2/bin/kubectl --kubeconfig=/etc/rancher/rke2/rke2.yaml $*' > /usr/local/bin/fpk
    [ $? -ne 0 ] && crit "Failed to create /usr/local/bin/fpk"
    run_cmd chmod +x /usr/local/bin/fpk

    info "Ensure /usr/local/bin is in PATH"
    if ! echo $PATH | grep -q "/usr/local/bin"; then
        echo 'export PATH=$PATH:/usr/local/bin' >> /$HOME/.bashrc
    fi
    export PATH=$PATH:/usr/local/bin

    info "Waiting for k8s to be ready"
    wait_for_k8s_ready 120
}

install_fp_helm_chart () {
    cat << EOF | fpk apply -f -
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: fairport
  namespace: kube-system
spec:
  chart: fairport
  version: 0.0.1
  repo: oci://gcr.io/fairport-io
  targetNamespace: fairport
  createNamespace: true
  timeout: 10m
  valuesContent: |-
    kube-prometheus-stack:
      enabled: false
    opensearch:
      enabled: false
    opensearch-dashboards:
      enabled: false
    opentelemetry-collector:
      enabled: false
EOF
}

install_fp_components () {
    install_fp_helm_chart
}

install_images () {
    if [ -f "$RKE2_IMAGE_FILE" ]; then
        info "Image file $RKE2_IMAGE_FILE already exists, skipping download"
        return 0
    fi

    info "Download images for installation to $RKE2_IMAGE_FILE"
    run_cmd mkdir -p $RKE2_IMAGE_DIR
    run_cmd curl -sL $RKE2_IMAGE_URL -o $RKE2_IMAGE_FILE
}

install () {
    if k8s_is_healthy && k8s_same_version; then
        info "K8s is already installed and the correct version is running"
        return 0
    fi

    install_images
    install_kubernetes
    install_fp_components
}

stop () {
    info "Stopping k8s"
    run_cmd /usr/local/bin/rke2-killall.sh
    exit 0
}

uninstall () {
    info "Uninstall k8s"
    run_cmd '/usr/local/bin/rke2-uninstall.sh || true'
    run_cmd 'rm -rf /var/lib/rancher || true'
    run_cmd 'rm -rf /etc/rancher || true'
    run_cmd 'rm -rf /usr/local/bin/rke*'
    exit 0
}

main () {
    check_debug
    check_dependencies
    echo "$@" | grep -q -- "stop" && stop
    echo "$@" | grep -q -- "uninstall" && uninstall
    check_variables
    install
}

main "$@"
